# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZivameDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire'
pod 'Kingfisher'
pod 'MBProgressHUD'
  # Pods for ZivameDemo

  target 'ZivameDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZivameDemoUITests' do
    # Pods for testing
  end

end
